<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXM8vaWy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXM8vaWy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXM8vaWy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXM8vaWy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXM8vaWy\App_KernelDevDebugContainer([
    'container.build_hash' => 'XM8vaWy',
    'container.build_id' => '8d66fbb6',
    'container.build_time' => 1665143353,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXM8vaWy');
